export const mock = [
  {
    first_Name: "Rémi",
    last_Name: "Gaillard",
    start_Date: "2022-02-17",
    department: "Sales",
    birth_Date: "1992-04-02",
    street: "1 square toudoudou",
    city: "New-York",
    state: "AL",
    zip_Code: "123",
  },
  {
    first_Name: "Steve",
    last_Name: "Estatof",
    start_Date: "2022-01-15",
    department: "Sales",
    birth_Date: "1993-06-02",
    street: "2 street roucoul",
    city: "Paris",
    state: "AS",
    zip_Code: "234",
  },
  {
    first_Name: "Francis",
    last_Name: "4L",
    start_Date: "2020-06-01",
    department: "Marketing",
    birth_Date: "1990-03-16",
    street: "5 avenue piafabec",
    city: "Lyon",
    state: "IL",
    zip_Code: "4",
  },
  {
    first_Name: "Geneviève",
    last_Name: "De Fontenay",
    start_Date: "1927-11-23",
    department: "Legal",
    birth_Date: "1823-01-30",
    street: "1 road ptéra",
    city: "Bourg-Palette",
    state: "AL",
    zip_Code: "9",
  },
  {
    first_Name: "John",
    last_Name: "Snow",
    start_Date: "2006-01-31",
    department: "Engineering",
    birth_Date: "2006-01-30",
    street: "7 avenue onyx",
    city: "Monaco",
    state: "KA",
    zip_Code: "994",
  },
  {
    first_Name: "Tibo",
    last_Name: "inShape",
    start_Date: "2021-11-22",
    department: "Human Ressources",
    birth_Date: "1990-04-06",
    street: "33 place artikodin",
    city: "Saturn",
    state: "WY",
    zip_Code: "32",
  },
  {
    first_Name: "Eric",
    last_Name: "Judor",
    start_Date: "2020-02-12",
    department: "Sales",
    birth_Date: "1987-04-08",
    street: "55 street fighter",
    city: "New-York",
    state: "IN",
    zip_Code: "332",
  },
  {
    first_Name: "Bugs",
    last_Name: "Bunny",
    start_Date: "2001-01-01",
    department: "Sales",
    birth_Date: "1993-04-22",
    street: "2 square round",
    city: "Brest",
    state: "LE",
    zip_Code: "999",
  },
  {
    first_Name: "Jamy",
    last_Name: "Gourmaud",
    start_Date: "2014-09-09",
    department: "Marketing",
    birth_Date: "1977-05-03",
    street: "5 avenue raclette",
    city: "Margeriaz",
    state: "NV",
    zip_Code: "73",
  },
  {
    first_Name: "Bob",
    last_Name: "Kelso",
    start_Date: "1942-01-23",
    department: "Legal",
    birth_Date: "1840-01-22",
    street: "4 road carapuce",
    city: "Bourg-en-bresse",
    state: "MP",
    zip_Code: "01",
  },
  {
    first_Name: "Mark",
    last_Name: "Zukerberg ",
    start_Date: "2003-03-03",
    department: "Engineering",
    birth_Date: "1970-03-09",
    street: "77 avenue starlink",
    city: "Mars",
    state: "OK",
    zip_Code: "777",
  },
  {
    first_Name: "Morticia",
    last_Name: "Adams",
    start_Date: "1999-12-31",
    department: "Human Ressources",
    birth_Date: "1992-04-15",
    street: "44 rue Sonnenfeld",
    city: "Seattle",
    state: "VA",
    zip_Code: "32",
  },
];
